//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedViewer.RssFilterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RssFilterService.IRssFilterService")]
    public interface IRssFilterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFilterService/FilterRssFeed", ReplyAction="http://tempuri.org/IRssFilterService/FilterRssFeedResponse")]
        System.Collections.Generic.Dictionary<string, System.Uri> FilterRssFeed(System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFilterService/FilterRssFeed", ReplyAction="http://tempuri.org/IRssFilterService/FilterRssFeedResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.Uri>> FilterRssFeedAsync(System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRssFilterServiceChannel : RSSFeedViewer.RssFilterService.IRssFilterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssFilterServiceClient : System.ServiceModel.ClientBase<RSSFeedViewer.RssFilterService.IRssFilterService>, RSSFeedViewer.RssFilterService.IRssFilterService {
        
        public RssFilterServiceClient() {
        }
        
        public RssFilterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssFilterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssFilterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssFilterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, System.Uri> FilterRssFeed(System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags) {
            return base.Channel.FilterRssFeed(feed, tags);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.Uri>> FilterRssFeedAsync(System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags) {
            return base.Channel.FilterRssFeedAsync(feed, tags);
        }
    }
}
