//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedViewer.MailingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailingService.IMailingService")]
    public interface IMailingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingService/SendFeedByEmail", ReplyAction="http://tempuri.org/IMailingService/SendFeedByEmailResponse")]
        void SendFeedByEmail(string senderEmail, string senderPassword, System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingService/SendFeedByEmail", ReplyAction="http://tempuri.org/IMailingService/SendFeedByEmailResponse")]
        System.Threading.Tasks.Task SendFeedByEmailAsync(string senderEmail, string senderPassword, System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailingServiceChannel : RSSFeedViewer.MailingService.IMailingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailingServiceClient : System.ServiceModel.ClientBase<RSSFeedViewer.MailingService.IMailingService>, RSSFeedViewer.MailingService.IMailingService {
        
        public MailingServiceClient() {
        }
        
        public MailingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendFeedByEmail(string senderEmail, string senderPassword, System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags) {
            base.Channel.SendFeedByEmail(senderEmail, senderPassword, feed, tags);
        }
        
        public System.Threading.Tasks.Task SendFeedByEmailAsync(string senderEmail, string senderPassword, System.Collections.Generic.Dictionary<string, System.Uri> feed, string[] tags) {
            return base.Channel.SendFeedByEmailAsync(senderEmail, senderPassword, feed, tags);
        }
    }
}
