//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedViewer.RssLoadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RssLoadService.IRssService")]
    public interface IRssService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssService/LoadFeed", ReplyAction="http://tempuri.org/IRssService/LoadFeedResponse")]
        System.Collections.Generic.Dictionary<string, System.Uri> LoadFeed(string[] rssFeedUris);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssService/LoadFeed", ReplyAction="http://tempuri.org/IRssService/LoadFeedResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.Uri>> LoadFeedAsync(string[] rssFeedUris);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRssServiceChannel : RSSFeedViewer.RssLoadService.IRssService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssServiceClient : System.ServiceModel.ClientBase<RSSFeedViewer.RssLoadService.IRssService>, RSSFeedViewer.RssLoadService.IRssService {
        
        public RssServiceClient() {
        }
        
        public RssServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, System.Uri> LoadFeed(string[] rssFeedUris) {
            return base.Channel.LoadFeed(rssFeedUris);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.Uri>> LoadFeedAsync(string[] rssFeedUris) {
            return base.Channel.LoadFeedAsync(rssFeedUris);
        }
    }
}
